export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const REQUEST_LIST = 'REQUEST_LIST';
export const RECEIVE_LIST = 'RECEIVE_LIST';
export const CHANGE_PAGE  = 'CHANGE_PAGE';
export const CHANGE_ITEMS_PER_PAGE  = 'CHANGE_ITEMS_PER_PAGE';